source_database:
  user: ADMIN
  password: Fluffyfatec123
  dsn: bdfluffy_medium
  config_dir: /Users/Wallet_bdfluffy
  wallet_location: /Users/Wallet_bdfluffy
  wallet_password: Fluffyfatec123
target_database:
  user: ADMIN
  password: Fluffyfatec123
  dsn: dwfluffy_medium
  config_dir: /Users/Wallet_dwfluffy
  wallet_location: /Users/Wallet_dwfluffy
  wallet_password: Fluffyfatec123
tables:
  - name: temporal
    extract_query: "SELECT
      TO_CHAR(PC_DATETIME_ORDER, 'DDMMYYYYHH24MISS') AS temporal_datetime_idn,
      PC_DATETIME_ORDER AS temporal_datetime,
      TO_CHAR(PC_DATETIME_ORDER, 'DDMMYYYY') AS temporal_date_idn,
      TO_DATE(TO_CHAR(PC_DATETIME_ORDER, 'DDMMYYYY'), 'DDMMYYYY') AS temporal_date
    FROM PRODUCT_COMMAND"
    insert_query: "INSERT INTO temporal (temporal_datetime_idn, temporal_datetime, temporal_date_idn, temporal_date, datetime_upload) VALUES (:1, :2, :3, :4, CURRENT_TIMESTAMP)"
    column_types:
      - name: temporal_datetime_idn
        type: string
      - name: temporal_datetime
        type: date
      - name: temporal_date_idn
        type: string
      - name: temporal_date
        type: date
  - name: products
    extract_query: "SELECT
    product_id,
    product_name,
    product_type
FROM Products"
    insert_query: "INSERT INTO Product (product_idn, product_name, product_type, datetime_upload) VALUES (:1, :2, :3, CURRENT_TIMESTAMP)"
    column_types:
      - name: product_idn
        type: int
      - name: product_name
        type: str
      - name: product_type
        type: str

#  - name: sales_fact
#    extract_query: "SELECT
#    c.command_number,
#    pc.PC_QUANTITY,
#    pc.PC_MEASUREMENT,
#    c.COMMAND_ID
#FROM COMMANDS c
#INNER JOIN PRODUCT_COMMAND pc ON c.COMMAND_ID = pc.COMMAND_ID"
#    insert_query: "INSERT INTO Sales_Fact (product_quantity, product_id,sf_value, datetime_upload ) VALUES (:1, :2, :3, CURRENT_TIMESTAMP)"
#    column_types:
#      - name: product_quantity
#        type: float
#      - name: product_id
#        type: int
#      - name: sf_value
#        type: str
#      - name: datetime_upload
#        type: date




